/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dev.mariolopez.xdesign.UI;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import dev.mariolopez.xdesign.Logic.GestorPedidos;
import dev.mariolopez.xdesign.Logic.Pedido;


/**
 *
 * @author mariolopez
 */
public class UI_ComparacionValores extends javax.swing.JFrame {
    
    private JTextField idField;
    private JLabel cantidadDecimalLabel;
    private JLabel cantidadBinariaLabel;
    private GestorPedidos gestorPedidos;


    /**
     * Creates new form UI_ComparacionValores
     */
    public UI_ComparacionValores() {
        super("Comparación de Valores");
        gestorPedidos = GestorPedidos.getInstance();
        initializeComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setSize(400, 200);
        setLocationRelativeTo(null);
    }
    
    private void initializeComponents() {
        idField = new JTextField(10);
        JButton buscarButton = new JButton("Buscar");
        buscarButton.addActionListener(this::buscarButtonActionPerformed);

        cantidadDecimalLabel = new JLabel("Cantidad Decimal: ");
        cantidadBinariaLabel = new JLabel("Cantidad Binaria: ");

        JPanel inputPanel = new JPanel();
        inputPanel.add(new JLabel("ID del pedido:"));
        inputPanel.add(idField);
        inputPanel.add(buscarButton);

        JPanel resultPanel = new JPanel(new GridLayout(2, 1));
        resultPanel.add(cantidadDecimalLabel);
        resultPanel.add(cantidadBinariaLabel);

        setLayout(new BorderLayout());
        add(inputPanel, BorderLayout.NORTH);
        add(resultPanel, BorderLayout.CENTER);
    }
    
    private void buscarButtonActionPerformed(ActionEvent e) {
        try {
            int id = Integer.parseInt(idField.getText());
            Pedido pedido = gestorPedidos.findPedidoById(id);
            if (pedido != null) {
                int cantidadDecimal = pedido.getCantidad();
                String cantidadBinaria = cantidadABinario(cantidadDecimal);

                cantidadDecimalLabel.setText("Cantidad Decimal: " + cantidadDecimal);
                cantidadBinariaLabel.setText("Cantidad Binaria: " + cantidadBinaria);
            } else {
                JOptionPane.showMessageDialog(this, "Pedido no encontrado.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Ingrese un ID válido.", "Error de Validación", JOptionPane.ERROR_MESSAGE);
        }
    }

    private String cantidadABinario(int cantidad) {
        if (cantidad == 0) {
            return "0";
        } else if (cantidad == 1) {
            return "1";
        } else {
            return cantidadABinario(cantidad / 2) + (cantidad % 2);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI_ComparacionValores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI_ComparacionValores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI_ComparacionValores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI_ComparacionValores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI_ComparacionValores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
