/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dev.mariolopez.xdesign.UI;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;

import dev.mariolopez.xdesign.Logic.GestorPedidos;
import dev.mariolopez.xdesign.Logic.Pedido;

import java.awt.BorderLayout;
import java.util.ArrayList;
import java.util.Iterator;

/**
 *
 * @author mariolopez
 */
public class UI_ListadoPedidos extends javax.swing.JFrame {

    private JTable table;
    private DefaultTableModel tableModel;

    /**
     * Creates new form UI_ListadoPedidos
     */
    public UI_ListadoPedidos() {
        setTitle("Listado de Pedidos");
        setSize(800, 400);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        tableModel = new DefaultTableModel();
        tableModel.setColumnIdentifiers(new String[]{"ID", "Tipo de Camiseta", "Talla", "Cantidad", "Código de Diseño", "Tipo de Pedido", "Dirección de Entrega", "Forma de Pago", "Teléfono", "Nombre Cliente"});
        table = new JTable(tableModel);
        loadTableData();

        JScrollPane scrollPane = new JScrollPane(table);
        add(scrollPane, BorderLayout.CENTER);
    }

    private void loadTableData() {
        GestorPedidos gestor = GestorPedidos.getInstance();
        Iterator<Pedido> iterator = gestor.getListaPedidos().iterator(); // Uso explícito de Iterator
        while (iterator.hasNext()) {
            Pedido pedido = iterator.next();
            tableModel.addRow(new Object[]{
                pedido.getId(),
                pedido.getTipoCamiseta(),
                pedido.getTalla(),
                pedido.getCantidad(),
                pedido.getCodigoDiseno(),
                pedido.getTipoPedido(),
                pedido.getDireccionEntrega(),
                pedido.getFormaPago(),
                pedido.getNumeroTelefonicoCliente(),
                pedido.getNombreCompletoCliente()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI_ListadoPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI_ListadoPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI_ListadoPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI_ListadoPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UI_ListadoPedidos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
