/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dev.mariolopez.xdesign.UI;

import java.awt.GridLayout;
import javax.swing.JButton;
import javax.swing.JFrame;

/**
 *
 * @author mariolopez
 */
public class UI_Navegacion extends javax.swing.JFrame {

    /**
     * Creates new form UI_Navegacion
     */
    public UI_Navegacion() {
        /*
        initComponents();
        */
        super("Sistema de Gestión de Pedidos");
        setLayout(new GridLayout(5, 1)); // Usamos GridLayout para organizar los botones

        // Botón para registro de pedidos
        JButton btnRegistroPedidos = new JButton("Registrar Pedidos");
        btnRegistroPedidos.addActionListener(e -> {
            UI_RegistroPedidos registroPedidos = new UI_RegistroPedidos(null);
            registroPedidos.setVisible(true);
        });

        // Botón para listar pedidos
        JButton btnListarPedidos = new JButton("Listar Pedidos");
        btnListarPedidos.addActionListener(e -> {
            UI_ListadoPedidos listarPedidos = new UI_ListadoPedidos();
            listarPedidos.setVisible(true);
        });

        // Botón para búsqueda y edición de pedidos
        JButton btnBuscarEditarPedidos = new JButton("Buscar/Editar Pedidos");
        btnBuscarEditarPedidos.addActionListener(e -> {
            UI_BusquedaEdicionPedidos buscarEditarPedidos = new UI_BusquedaEdicionPedidos();
            buscarEditarPedidos.setVisible(true);
        });

        // Botón para la comparación de valores
        JButton btnCompararValores = new JButton("Comparar Valores");
        btnCompararValores.addActionListener(e -> {
            UI_ComparacionValores compararValores = new UI_ComparacionValores();
            compararValores.setVisible(true);
        });

        // Botón para el ordenamiento de pedidos
        JButton btnOrdenarPedidos = new JButton("Ordenar Pedidos");
        btnOrdenarPedidos.addActionListener(e -> {
            UI_OrdenamientoPedidos ordenarPedidos = new UI_OrdenamientoPedidos();
            ordenarPedidos.setVisible(true);
        });

        // Añadir botones al layout
        add(btnRegistroPedidos);
        add(btnListarPedidos);
        add(btnBuscarEditarPedidos);
        add(btnCompararValores);
        add(btnOrdenarPedidos);

        setSize(300, 300); // Tamaño de la ventana
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null); // Centrar en pantalla
    }

        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegistroPedidos = new javax.swing.JButton();
        btnListarPedidos = new javax.swing.JButton();
        btnBuscarEditarPedidos = new javax.swing.JButton();
        btnCompararValores = new javax.swing.JButton();
        btnOrdenarPedidos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnRegistroPedidos.setText("Registrar Pedido");

        btnListarPedidos.setText("Listar Pedidos");

        btnBuscarEditarPedidos.setText("Buscar y Editar Pedidos");

        btnCompararValores.setText("Comparar Valores");

        btnOrdenarPedidos.setText("Ordenamiento de Pedidos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnOrdenarPedidos)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnListarPedidos)
                            .addComponent(btnRegistroPedidos))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCompararValores)
                            .addComponent(btnBuscarEditarPedidos))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBuscarEditarPedidos)
                        .addGap(18, 18, 18)
                        .addComponent(btnCompararValores))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRegistroPedidos)
                        .addGap(18, 18, 18)
                        .addComponent(btnListarPedidos)))
                .addGap(18, 18, 18)
                .addComponent(btnOrdenarPedidos)
                .addContainerGap(153, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI_Navegacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI_Navegacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI_Navegacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI_Navegacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI_Navegacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarEditarPedidos;
    private javax.swing.JButton btnCompararValores;
    private javax.swing.JButton btnListarPedidos;
    private javax.swing.JButton btnOrdenarPedidos;
    private javax.swing.JButton btnRegistroPedidos;
    // End of variables declaration//GEN-END:variables
}
