/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dev.mariolopez.xdesign.UI;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.util.ArrayList;

import dev.mariolopez.xdesign.Logic.GestorPedidos;
import dev.mariolopez.xdesign.Logic.Pedido;

/**
 *
 * @author mariolopez
 */
public class UI_OrdenamientoPedidos extends javax.swing.JFrame {
    
    private JButton ordenarPorTelefonoButton;
    private JButton ordenarPorCodigoButton;
    private JTable pedidosTable;
    private DefaultTableModel model;
    private GestorPedidos gestorPedidos;

    /**
     * Creates new form UI_OrdenamientoPedidos
     */
    public UI_OrdenamientoPedidos() {
        super("Ordenamiento de Pedidos");
        gestorPedidos = GestorPedidos.getInstance();
        initializeComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setSize(800, 400);
        setLocationRelativeTo(null);
    }
    
    private void initializeComponents() {
        ordenarPorTelefonoButton = new JButton("Ordenar por Teléfono (Inserción)");
        ordenarPorCodigoButton = new JButton("Ordenar por Código (Merge Sort)");

        ordenarPorTelefonoButton.addActionListener(this::ordenarPorTelefono);
        ordenarPorCodigoButton.addActionListener(this::ordenarPorCodigo);

        model = new DefaultTableModel();
        model.setColumnIdentifiers(new String[]{"ID", "Tipo de Camiseta", "Talla", "Cantidad", "Código de Diseño", "Tipo de Pedido", "Dirección", "Forma de Pago", "Teléfono", "Nombre Cliente"});
        pedidosTable = new JTable(model);
        JScrollPane scrollPane = new JScrollPane(pedidosTable);

        JPanel buttonPanel = new JPanel();
        buttonPanel.add(ordenarPorTelefonoButton);
        buttonPanel.add(ordenarPorCodigoButton);

        setLayout(new BorderLayout());
        add(buttonPanel, BorderLayout.NORTH);
        add(scrollPane, BorderLayout.CENTER);
    }

    private void ordenarPorTelefono(ActionEvent e) {
        gestorPedidos.ordenarPorTelefonoInsercion();
        actualizarTabla(gestorPedidos.getListaPedidos());
    }

    private void ordenarPorCodigo(ActionEvent e) {
        gestorPedidos.ordenarPorCodigoDisenoMergeSort();
        actualizarTabla(gestorPedidos.getListaPedidos());
    }

    private void actualizarTabla(ArrayList<Pedido> pedidos) {
        model.setRowCount(0); // Clear previous results
        for (Pedido p : pedidos) {
            model.addRow(new Object[]{p.getId(), p.getTipoCamiseta(), p.getTalla(), p.getCantidad(), p.getCodigoDiseno(), p.getTipoPedido(), p.getDireccionEntrega(), p.getFormaPago(), p.getNumeroTelefonicoCliente(), p.getNombreCompletoCliente()});
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI_OrdenamientoPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI_OrdenamientoPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI_OrdenamientoPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI_OrdenamientoPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UI_OrdenamientoPedidos().setVisible(true));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
